version: '3.8'
services:
  webserver:
    image: nginx
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - production-network
    depends_on:
      - 'app'
  app:
    build:
      dockerfile: ./docker/gobarber-back.Dockerfile
      context: .
    container_name: backend
    image: gobarber/backend
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    depends_on:
      - 'barberdb'
      - 'barbermongo'
      - 'barberredis'
    command: typeorm migration:run
    networks:
      - production-network
  barberdb:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: gobarber
    networks:
      - production-network
    ports:
      - 5432:5432
  barbermongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - production-network
  barberredis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - production-network
networks:
  production-network:
    driver: bridge
